### ISSUE TITLE
Questions about training event on Thursday 9th December

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#110]

**Comment by GretaTimaite** [comment]
Map after running the script!

<img width="1440" alt="Screenshot 2021-12-07 at 15 51 51" src="https://user-images.githubusercontent.com/84614994/145062518-b5439b5b-cf37-4d74-bfc6-819487a22aec.png">

**Comment by Robinlovelace** [comment]
That is great to see! Thanks Greta. Glad to hear of more feedback on what people saw after running the script, before and after. For what it's worth this is what is see, including the R console in RStudio where I put the code and pressed Enter to run it.

![image](https://user-images.githubusercontent.com/1825120/145066516-d8f9cd12-508e-4a68-a795-7f943be537e0.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/145405409-b2b6ea22-6b39-4d6a-9aaa-08065988d31b.png)
