### ISSUE TITLE
Add PCT -> A/B Street example

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#112]
- [x] In training document
- [ ] In vignette

**Comment by Robinlovelace** [comment]
Latest version of the guide: https://github.com/ITSLeeds/pct/releases/download/v0.9.4/training-dec-2021.html

Source: https://github.com/ITSLeeds/pct/blob/master/data-raw/training-dec-2021.Rmd

**Comment by dabreegster** [comment]
I can help write this later tonight or early tomorrow. The steps I'd lead people through:

1) Install A/B Street locally, which is needed for importing new maps. https://a-b-street.github.io/docs/user/index.html#installing-ab-street
2) Import York by following https://a-b-street.github.io/docs/user/new_city.html#the-easy-method
3) Produce the scenario.json file by following the R instructions
4) Import the scenario.json file in the UI (I'll add screenshots)

I would say we could edit this York map and then share a URL with the proposal, but that won't work for imported maps. So I might show that off in Leeds instead.

**Comment by Robinlovelace** [comment]
Great stuff. Will aim to generate a scenario.json file for Leeds also as a bonus, the code should work anywhere as the PCT tool and data provision is national.

**Comment by Robinlovelace** [comment]
Case study area is pretty big! Will constrain it...

![image](https://user-images.githubusercontent.com/1825120/145102247-1ec36e32-84f1-4b56-8d6d-93d764ac73bf.png)

**Comment by Robinlovelace** [comment]
Building footprint for all of York local authority still seems unwieldy, too big for each example...

![image](https://user-images.githubusercontent.com/1825120/145109894-01c1aae7-8517-46f3-b01d-db8d4a2920a1.png)

**Comment by Robinlovelace** [comment]
5km buffer looks better

![image](https://user-images.githubusercontent.com/1825120/145110575-9ce7ed11-cf5d-4d54-b40f-504a12e130e0.png)

**Comment by Robinlovelace** [comment]
![Peek 2021-12-08 00-32](https://user-images.githubusercontent.com/1825120/145127122-b88e9f02-3069-4bdd-8f6d-6c3512ee3ac5.gif)

Result for central/north Leeds generated with the code in #113.

It works! Sooo many people walking.

**Comment by dabreegster** [comment]
I'm going to use your trick for hosting images...
![Screenshot from 2021-12-08 08-05-34](https://user-images.githubusercontent.com/1664407/145171484-b8c34f04-92a7-4e69-b3ea-761e714e75b2.png)
![Screenshot from 2021-12-08 08-07-23](https://user-images.githubusercontent.com/1664407/145171705-36b221a6-f63b-47d6-8fb5-4e187508696c.png)
![Screenshot from 2021-12-08 08-08-22](https://user-images.githubusercontent.com/1664407/145171832-44270223-d3a6-4028-9586-6e5efb82c52c.png)
![Screenshot from 2021-12-08 08-15-46](https://user-images.githubusercontent.com/1664407/145173134-3865e98b-ebd1-4808-8e1b-2697192a98d1.png)
![Screenshot from 2021-12-08 08-18-22](https://user-images.githubusercontent.com/1664407/145173156-85d32d77-27ce-4813-b7e8-fff962a09cae.png)

**Comment by dabreegster** [comment]
![Screenshot from 2021-12-08 08-12-20](https://user-images.githubusercontent.com/1664407/145173423-4c5468a1-fae1-4605-8db5-f5a201fae56c.png)

**Comment by dabreegster** [comment]
![Screenshot from 2021-12-08 09-40-24](https://user-images.githubusercontent.com/1664407/145185679-7ec2f0bc-52e9-4aef-8e88-0b8154022744.png)
![Screenshot from 2021-12-08 09-48-54](https://user-images.githubusercontent.com/1664407/145186873-a8b8c3a3-9833-4ef8-85f3-ad38b049c72e.png)
![Screenshot from 2021-12-08 09-47-23](https://user-images.githubusercontent.com/1664407/145186876-c7091281-8c1c-446f-97ae-4cd676162a22.png)
![Screenshot from 2021-12-08 09-47-06](https://user-images.githubusercontent.com/1664407/145186881-f9f4532f-ac18-40d1-a177-dd5ea347d83e.png)
![Screenshot from 2021-12-08 09-42-58](https://user-images.githubusercontent.com/1664407/145186889-f32c55f4-e3e2-4958-9cf9-aa1f70b15275.png)

**Comment by dabreegster** [comment]
![Screenshot from 2021-12-08 10-03-50](https://user-images.githubusercontent.com/1664407/145189298-84e1fd1c-a398-4cc6-af78-917326353bde.png)
![Screenshot from 2021-12-08 10-03-39](https://user-images.githubusercontent.com/1664407/145189302-aec4b6cd-3b4b-4f40-9aca-b6bdf30081ab.png)
![Screenshot from 2021-12-08 10-02-22](https://user-images.githubusercontent.com/1664407/145189310-01e8624d-ce50-4fb7-91a1-7b647676f31d.png)
![Screenshot from 2021-12-08 10-01-12](https://user-images.githubusercontent.com/1664407/145189320-1d22d7ee-8ebf-4446-8923-34da097d60c9.png)
![Screenshot from 2021-12-08 09-59-50](https://user-images.githubusercontent.com/1664407/145189325-55c6f809-0938-4ab9-b848-4877c9a1f706.png)
![Screenshot from 2021-12-08 09-59-09](https://user-images.githubusercontent.com/1664407/145189329-c7066424-ee65-4a72-b6b1-b56daf7a4cbe.png)
![Screenshot from 2021-12-08 09-56-14](https://user-images.githubusercontent.com/1664407/145189333-e6ca7fac-ad26-4a06-8a3c-21ee3ed43213.png)

**Comment by Robinlovelace** [comment]
Looking good!
