### ISSUE TITLE
Cycling levels for specific links / roads

### ISSUE THREAD

**Issue by georgie5995** [ITSLeeds/pct#117]
Hi, I was looking for some assistance working out how to extract existing cycling levels on specific roads/links. It would also be useful to extract the cycling levels within each model scenario (Government target, Ebike, etc.). I am hoping to generate an excel / CSV with the road name / link name and corresponding existing cycling levels for that link / road (+ levels under the modelled scenarios). The link / roads would be within a certain area (e.g. within Hyde Park, Leeds), so I imagine I would need to first create a buffer zone within which data is extracted? Any help generating an RScript would be much appreciated. Thanks! Georgie Carpenter

**Comment by Robinlovelace** [comment]
Hi there @georgie5995 yes this is doable. Do you have a dataset containing the roads? A geographic join should sort it. If you could share an example dataset I can put together a reproducible example to show how to allocate cycling potential to specific road segments.
