### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by layik** [ITSLeeds/pct#12]
- [x] Win build report sent
- [x]  `goodpractice` results are just about use of `<-`.
- [x]  Minimal vignette (after README is done, split-out long parts from it like in `stats19`)
- [ ] ...

**Comment by layik** [comment]
https://win-builder.r-project.org/J6LZEn5Oysjo/00check.log

**Comment by layik** [comment]
Vignette assigned to me.

**Comment by layik** [comment]
So vignette is pending other package dev and especially what goes into README.

So the right question to ask: have we got enough to prepare for 0.01?

**Comment by Robinlovelace** [comment]
> So the right question to ask: have we got enough to prepare for 0.01?

I think so.

**Comment by layik** [comment]
Right, I can start working on the vignette.

**Comment by layik** [comment]
The vignette would do with some touches from you @Robinlovelace as my `ggplot` and PCT knowledge is limited.

**Comment by layik** [comment]
But it is acceptable, I think, for CRAN.

**Comment by layik** [comment]
Another winbuild sent

**Comment by Robinlovelace** [comment]
Sure. I'll take a look at polishing the vignettes now. Many thanks @layik .

**Comment by layik** [comment]
OK I am going to go through these.
https://github.com/ropensci/software-review/issues/266#issuecomment-450324567

**Comment by layik** [comment]
`winbuild` still failing and it seems to do with get_pct, testing on actual windows
```
Status: 4 ERRORs, 2 WARNINGs, 1 NOTE
R Under development (unstable) (2019-03-19 r76252)```
https://win-builder.r-project.org/aaaX20tsu0zi/00check.log

**Comment by Robinlovelace** [comment]
Good find. Over to you on debugging...

**Comment by layik** [comment]
Package runs on Windows.

**Comment by Robinlovelace** [comment]
Thanks. My plan: polish-up the vignettes and then submit. Great work on getting win check working!

**Comment by layik** [comment]
Great work on getting the vignettes "build" smoothly. Are we able to submit? :)

**Comment by Robinlovelace** [comment]
Almost but want to get it right. See issues... No rush.

**Comment by layik** [comment]
Shall we do #38 then? I just so the "no rush".

**Comment by Robinlovelace** [comment]
I think it's good to go and you're right, can be addressed in the next version. One think though, CRAN now prefer packages to have a doi in their Description field. See here: https://github.com/ropensci/stplanr/blob/master/DESCRIPTION#L24

I suggest adding the doi of the PCT paper.

**Comment by layik** [comment]
is that it?

**Comment by Robinlovelace** [comment]
I think so. Happy for you to to release it!

**Comment by layik** [comment]
I will!
https://github.com/ITSLeeds/pct/commit/26a11d7998b6b6398377327e495d934b8ec650e8

based on 
http://r-pkgs.had.co.nz/release.html#release-check

**Comment by layik** [comment]
```
Submitting file: /tmp/RtmpzzbudB/pct_0.1.0.tar.gz
File size: 1.7 Mb
Uploading package & comments
Confirming submission
Package submission successful.
Check your email for confirmation link.
Don't forget to tag this release once accepted by CRAN
✔ Setting active project to '/home/layik/code/pct'
✔ Adding '^CRAN-RELEASE$' to '.Rbuildignore'
```
