### ISSUE TITLE
Package was removed from the CRAN repository?

### ISSUE THREAD

**Issue by Whissi** [ITSLeeds/pct#120]
Today we tried to rebuild our docker container which is using pct package. It failed with

> Error: dependency ‘pct’ is not available

While checking logs I run into https://cran.r-project.org/web/packages/pct/index.html which says

![image](https://user-images.githubusercontent.com/729436/204330557-2fc184a2-61a0-4775-bbb5-0902c2888c29.png)

Are you aware of this and maybe already working on getting the package back into repository or do I have to manually add it to our container?

**Comment by Robinlovelace** [comment]
Heads-up @Whissi this is now back on CRAN. Please take a look and confirm it works for you. Also, any other issues you find with the package please do let us know here. Thanks!

**Comment by Whissi** [comment]
Still not working yet.

If I am not mistaken, error turned into a warning:
> Warning: dependency ‘pct’ is not available

I changed `Dockerfile` a bit to try for `pct` at the beginning and error is
```
STEP 3: RUN install2.r --error  --deps TRUE     pct
Error: package ‘pct’ is not available for this version of R
```

**Comment by Robinlovelace** [comment]
What system are you on?

**Comment by Robinlovelace** [comment]
Thought: you're using an old version of the cran archive.

**Comment by Whissi** [comment]
My reduced `Dockerfile` looks like
```
FROM rocker/tidyverse:latest

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        libodbc1 \
        odbc-postgresql \
        libxml2 \
        libudunits2-dev \
        libgdal-dev \
        libgeos-dev \
        libproj-dev \
        libxt-dev \
        libglpk-dev \
        libsecret-1-dev \
        libsodium-dev \
        git \
        patch \
        && apt-get clean \
        && apt-get purge \
        && rm -rf /var/lib/apt/lists/*

RUN install2.r --error \
        --deps TRUE \
        pct
```

**Comment by Whissi** [comment]
I did that:

```
$ podman image ls | grep tidy
docker.io/rocker/tidyverse  latest  a838ee142831  4 weeks ago     2.18 GB
$ podman image inspect a838ee142831 | head -n 10
[
    {
        "Id": "a838ee1428319cb1a3cb6fe9267042ce1e0ca62e199cbb1c6709e28c94ba89d1",
        "Digest": "sha256:c37471e216914a7e7ff7ac040f0b993b6e2fc62cae8cea1fae25acdf45f30ec4",
        "RepoTags": [
            "docker.io/rocker/tidyverse:latest"
        ],
        "RepoDigests": [
            "docker.io/rocker/tidyverse@sha256:c37471e216914a7e7ff7ac040f0b993b6e2fc62cae8cea1fae25acdf45f30ec4"
        ],
```
Digest matches latest tag shown at https://hub.docker.com/r/rocker/tidyverse/tags.

It probably just takes a little bit more time, i.e. it's not yet listed in today's snapshot at https://cran.microsoft.com/snapshot/2022-12-06/ for example but was listed one month ago https://cran.microsoft.com/snapshot/2022-11-06/ (NOTE: I don't use Microsoft's mirror but it's the only one I found providing snapshots to proof my point).

**Comment by Whissi** [comment]
Thank you for your help. Package is now also available via normal repos.
