### ISSUE TITLE
Add pct_regions object

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#17]
I'm up for doing this one. Was thinking of creating look-up between local authorities and our regions, that would be useful and is probably in our code somewhere already.

**Comment by Robinlovelace** [comment]
Heads-up @layik here's a reprex that gets them in a decent and suitably compressed form:

``` r
pct_regions = sf::read_sf("https://github.com/npct/pct-shiny/raw/master/regions_www/pct_regions_highres.geojson")
pryr::object_size(pct_regions)
#> 458 kB
pct_regions = rmapshaper::ms_simplify(pct_regions, keep = 0.1,)
pryr::object_size(pct_regions)
#> 81.8 kB
pct_regions = pct_regions[2]
plot(pct_regions)
```

![](https://i.imgur.com/8oBK9Tc.png)

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


Data source: https://github.com/npct/pct-shiny/blob/master/regions_www/pct_regions_highres.geojson

**Comment by layik** [comment]
Awesome @Robinlovelace thanks!
