### ISSUE TITLE
Travis failing - sf > rgdal

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#18]
This is super useful, many thanks @edzer for providing this template that seems solid: https://github.com/edzer/sf_dep/blob/master/.travis.yml

**Comment by layik** [comment]
That's what we have been using. We do need `libgdal-dev` and `rgdal` R package.

**Comment by layik** [comment]
https://travis-ci.org/ITSLeeds/pct/builds/504736762#L1390

Nothing to do with this afternoon's work. Something not quite right over at Travis or even further upstream.

**Comment by Robinlovelace** [comment]
Aha yes, I see it's a Suggests for sf: https://github.com/r-spatial/sf/blob/master/DESCRIPTION#L79

**Comment by layik** [comment]
Let us see https://github.com/ITSLeeds/pct/commit/a37ef8c6b6059f987b2724ce229f3b8b1975a7b9

**Comment by layik** [comment]
Right, `sf` has an issue with its "suggested" dependency on `rgdal`.

**Comment by layik** [comment]
I played with this when Travis started having this issue, and removed the branch. Let's try again.

This is a build on branch `rgdal` which corresponds to a successful `master` build commit hash.
https://travis-ci.org/ITSLeeds/pct/builds/505188742?utm_source=github_status&utm_medium=notification

**Comment by layik** [comment]
Same issue.
https://travis-ci.org/ITSLeeds/pct/builds/505188742#L1068

**Comment by Robinlovelace** [comment]
Heads-up, I think this will be fixed upstream based on this: https://github.com/r-spatial/sf/issues/1002

**Comment by layik** [comment]
Awesome, well spotted! My email to `rgdal` guys was rejected as I am still not "approved" subscriber I think, but this should do the trick.

**Comment by layik** [comment]
A better look than traveler brain yesterday:

1. Wait for `sf` to update on CRAN
2. [This](https://github.com/r-spatial/sf/commit/314bf44cb36235414cda730dc46fcb5c22efdcdd) way

```
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
```

**Comment by Robinlovelace** [comment]
Or this way: https://github.com/ITSLeeds/pct/pull/21

**Comment by layik** [comment]
Edited my comment above as the "tic" package might be something `sf` does outside the main package.

**Comment by layik** [comment]
Yay built finally. https://travis-ci.org/ITSLeeds/pct/builds/505697915?utm_source=github_status&utm_medium=notification
