### ISSUE TITLE
generate_pct(scenario = "goducth", ...)

### ISSUE THREAD

**Issue by layik** [ITSLeeds/pct#25]
The ultimate goal of this package. In other words, this could do what the right panel does:
![image](https://user-images.githubusercontent.com/408568/54348432-ed06ae00-4640-11e9-83e5-e56cd4befbe2.png)

**Comment by Robinlovelace** [comment]
Yep with option to do it for local authorities (those regions are huge) and with an `n = ...` arg to determine number of routes to be calculated.
