### ISSUE TITLE
Split pct vignette into 'Obtaining and visualising data from the PCT' and 'Reproducing the results of the PCT'?

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#38]
Just an idea. When I look at this, it seems rather long and I think it would be easier for others, particularly beginners, to digest if the two parts were in separate vignettes. Downside: would be a little more work. Thoughts @layik ? Almost there!

**Comment by layik** [comment]
Good Monday morning @Robinlovelace. Great work over the weekend. I am happy either way. I think a long vignette would be fine :) perfections can come in later. We can leave the ticket hanging for post CRAN but either way.

**Comment by layik** [comment]
post CRAN submission**

**Comment by Robinlovelace** [comment]
Sounds good.
