### ISSUE TITLE
Bosh CRAN issues

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#39]
- [x] How the doi is entered in the readme

Can put other issues here. See message below.

**Comment by Robinlovelace** [comment]
Log dir: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.0_20190325_135007/>
The files will be removed after roughly 7 days.
Installation time in seconds: 7
Check time in seconds: 171
R Under development (unstable) (2019-03-24 r76263)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.0_20190325_135007/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.0_20190325_135007/Debian/00check.log>
Status: 1 NOTE



No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: NOTE
  Maintainer: 'Robin Lovelace <rob00x@gmail.com>'

  New submission

  The Description field contains
    <http://dx.doi.org/10.5198/jtlu.2016.862>.
  Please write DOIs as <doi:10.prefix/suffix>.

**Comment by layik** [comment]
DESCRIPTION you meant and not README.

**Comment by Robinlovelace** [comment]
Yes. Resubmitted :+1: 

```

CRAN submission <cran-sysadmin@xmpalantir.wu.ac.at> | CRAN submission <cran-sysadmin@xmpalantir.wu.ac.at> | 4:17 PM (0 minutes ago)
-- | -- | --
CRAN submission <cran-sysadmin@xmpalantir.wu.ac.at>


```

**Comment by Robinlovelace** [comment]
Heads-up @layik here's an update from CRAN:

package pct_0.1.1.tar.gz has been auto-processed and is pending a manual inspection of this new CRAN submission. A CRAN team member will typically respond to you within the next 10 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

Log dir: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.1_20190325_181842/>
The files will be removed after roughly 7 days.
Installation time in seconds: 6
Check time in seconds: 140
R Under development (unstable) (2019-03-24 r76263)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.1_20190325_181842/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/pct_0.1.1_20190325_181842/Debian/00check.log>
Status: 1 NOTE

**Comment by layik** [comment]
Thanks @Robinlovelace, on the debian log, I could not see the "NOTE". Could you?

**Comment by layik** [comment]
Thanks for the resubmit, we could keep this ticket open if need be.
