### ISSUE TITLE
Add interface to the cyclestreets package that downloads route segment characteristics

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#4]
This package provides routes, with busyness estimates: https://github.com/Robinlovelace/cyclestreets

E.g. (after you have an api key):

``` r
o = stplanr::geo_code("chapeltown")
d = stplanr::geo_code("university of leeds")
r = cyclestreets::journey(from = o, to = d, plan = "fastest")
plot(r)
```

![](https://i.imgur.com/wxA1dE2.png)

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by layik** [comment]
Are we pushing ahead with this @Robinlovelace?

**Comment by Robinlovelace** [comment]
Non-essential, so closing for now. We can always re-open.
