### ISSUE TITLE
Centroids data has moved

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#46]
Causing tests to fail. Heads-up @layik. I'm working on a solution.

``` r
u = paste0("https://opendata.arcgis.com/datasets/",
           "b0a6d8a3dc5d4718b3fd62c548d60f81_0.csv")
pwc = readr::read_csv(u)
#> Error in open.connection(con, "rb"): HTTP error 502.
```

<sup>Created on 2019-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by layik** [comment]
Thanks Robin. Apologies for lack of input.

**Comment by Robinlovelace** [comment]
Now worries. safer roads = priority!
