### ISSUE TITLE
Issue with route network download

### ISSUE THREAD

**Issue by ailishgraham** [ITSLeeds/pct#50]
``` r
library(pct)
    cycling_popularity = get_pct_rnet("isle-of-wight")
#> Warning in utils::download.file(url = u_file, destfile = destfile, mode
#> = "wb"): cannot open URL 'https://github.com/npct/pct-outputs-regional-R/
#> raw/master/commute/msoa/isle-of-wight/rnet.Rds': HTTP status was '404 Not
#> Found'
#> Error in utils::download.file(url = u_file, destfile = destfile, mode = "wb"): cannot open URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/rnet.Rds'
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Robinlovelace** [comment]
Thanks for raising the issue @ailishgraham. I think the issue is fixed in the latest version - try installing it, restarting your R session, and re-running the reproducible example. I get this:

``` r
library(pct)
    cycling_popularity = get_pct_rnet("isle-of-wight")
#> No MSOA route network data available, downloading LSOA data
#> Loading required package: sp
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Works fine for now so closing. Any other issues you find, let us know. Thanks for reporting @ailishgraham !
