### ISSUE TITLE
Error: invalid crs: +proj=longlat +init=epsg:4326 +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0, reason: no arguments in initialization list

### ISSUE THREAD

**Issue by eugenividal** [ITSLeeds/pct#56]
I got this error trying to run z <- pct::get_pct(layer = "z", geography = "lsoa", national = TRUE). However, following @Robinlovelace suggestions I could solve it once I re-installed rgdal package!

**Comment by Robinlovelace** [comment]
Thanks for the info. If anyone else has this issue, just update your packages, e.g. with the command:

```
update.packages(ask = FALSE)
```

Thanks @eugenividal and bon chance!
