### ISSUE TITLE
Fixes for CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#64]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_pct.html>.

Please correct before 2020-06-28 to safely retain your package on CRAN.

**Comment by layik** [comment]
Me was like, is this auto-generated :)

**Comment by Robinlovelace** [comment]
Fixed :tada: 

https://cran.r-project.org/web/packages/pct/index.html
