### ISSUE TITLE
Issues/questions on the PCT Advanced Workshop

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#74]
In preparation for the [course on 12th November](https://hopin.to/events/propensity-to-cycle-tool-advanced-training-workshop), please reply to this thread to check GitHub is working. You can also use this thread as a place to ask questions and get help.

![image](https://user-images.githubusercontent.com/1825120/98568567-24f84580-22a9-11eb-83a5-783c013a6560.png)

**Comment by Robinlovelace** [comment]
Here's some output you should be able to get by running the code here: https://github.com/ITSLeeds/pct/blob/master/inst/test-setup.R

![image](https://user-images.githubusercontent.com/1825120/98556481-fffcd600-229a-11eb-9859-9f16850f07cd.png)

**Comment by RichardCalton** [comment]
Hi

**Comment by Robinlovelace** [comment]
Hi @RichardCalton, thanks for the message.

**Comment by zaeraa** [comment]
Hi, everything working for me

**Comment by jpb2288** [comment]
Hi there

**Comment by sridharraman** [comment]
Hi

**Comment by benmitchell92** [comment]
Hi

**Comment by mbcmn** [comment]
Hi

**Comment by charliefarlie47** [comment]
Hi!

**Comment by david-dyer** [comment]
Hi

**Comment by kipetrova** [comment]
Hi

**Comment by SandhyaGorinta** [comment]
Hi, everything is working for me.

**Comment by manuelapiase** [comment]
Hi! I'll try my best today as colleagues forwarded to me the course only on Tuesday afternoon and yesterday and this morning I was busy all day in an international meeting. I haven't use R in many years. I will try to run the code now and finger crossed!

**Comment by justin-yim** [comment]
Hi!

**Comment by samgreening25** [comment]
Hi!

**Comment by rachelseymour** [comment]
Hi!

**Comment by kbar60** [comment]
hi
