### ISSUE TITLE
Contributing guidelines / How to get involved

### ISSUE THREAD

**Issue by ccamara** [ITSLeeds/pct#76]
I just discovered PCT two days ago (congratulations!), so I am still figuring out how it works and its basic concepts. 

As a learning by doing proponent, I was considering if there are ways to collaborate on the project, so I can learn while contributing to the project. After checking issue queue, however, as a newcomer, I have not been able to understand your needs because I lack some context (other than splitting vignettes #38 , which I may attempt to do) nor good first-issues. 

Are you interested in any type of contributions?

**Comment by Robinlovelace** [comment]
Hi @ccamara, many thanks for asking the question - this is a great way towards getting involved. I think there a number of good starter issues, some of which I plan to open and tag with good first issue, as I have done for this one. I learned lots of my R by making small contributions to projects and, as you say, learning by doing is a great strategy. I would be most grateful for your input on #38 and any other feedback/contributions/PR!
