### ISSUE TITLE
Obsolete function 'line2route()' still present in vignettes

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#77]
Following #76, I noticed a documentation issue:

```
vignettes/pct-international.Rmd
129:santiago_routes_cs = stplanr::line2route(desire_lines)

vignettes/pct.Rmd
267:wight_routes_fast = line2route(
```

Problem: the function no longer exists! It has been replaced by the function `route()` and should be adapted as follows:

```
stplanr::route(l = desire_lines)
```

That may create additional issues in terms of reproducibility but for now switching those is worth doing.

**Comment by ccamara** [comment]
I tried to get started with this one. Just to make sure: I have seen, though, that ` line2route()` still exists in [`stplanr` documentation](https://docs.ropensci.org/stplanr/reference/line2route.html) and is still available in the latest cran version (0.8).

**Comment by Robinlovelace** [comment]
Hi @ccamara, good point :facepalm: assumed that when I created the `route()` function I removed the older `line2route()` function... Seems it's still there and working, as per the reprex below. What do you think we should do, leave it as is? Advantage of `route()` with the cyclestreets  `journey()` function is that it returns data at the segment level, including the 'busyness' of each segment rather than aggregates over the whole route:

``` r
library(stplanr)
l <- flowlines[2:5, ]
r <- line2route(l)
mapview::mapview(r)
```

![](https://i.imgur.com/6ihB7Tm.png)

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
FYI, here is an example of where I replaced one of the existing instances of `line2route()`: https://github.com/ITSLeeds/pct/commit/54863cd1654c5876480dfc70b8783dddf7f8445f#diff-8afb26e5ed777617d6c1bba656e73e239aa283d9018346deb66db41cb430e871L267
