### ISSUE TITLE
Demonstration of the approach for other cities

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#78]
Reproducible example shown below for Cardiff. Any other examples from other cities welcome. Should we add this to a new vignette? Thoughts welcome @layik, @ccamara or anyone.

``` r
install.packages("remotes", quiet = TRUE)
remotes::install_cran("pct", dependencies = "Suggests")
#> Skipping install of 'pct' from a cran remote, the SHA1 (0.6.0) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

region_name = "wales"
la_name = "Cardiff"


zones_all = pct::get_pct_zones(region_name)
unique(zones_all$lad_name)
#>  [1] "Cardiff"               "Wrexham"               "Conwy"                
#>  [4] "Newport"               "Caerphilly"            "Rhondda Cynon Taf"    
#>  [7] "Carmarthenshire"       "Swansea"               "The Vale of Glamorgan"
#> [10] "Bridgend"              "Neath Port Talbot"     "Pembrokeshire"        
#> [13] "Denbighshire"          "Flintshire"            "Monmouthshire"        
#> [16] "Powys"                 "Torfaen"               "Blaenau Gwent"        
#> [19] "Ceredigion"            "Gwynedd"               "Merthyr Tydfil"       
#> [22] "Isle of Anglesey"
zones = zones_all %>% 
  filter(lad_name == la_name)
plot(zones["bicycle"])
```

![](https://i.imgur.com/JW9WN99.png)

``` r
rnet_all = pct::get_pct_rnet(region_name)
# rnet = rnet_all[zones, , op = sf::st_within]
rnet = rnet_all[zones, ]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(zones$geometry)
plot(rnet["dutch_slc"], add = TRUE)
```

![](https://i.imgur.com/PW93Lo4.png)

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by natesheehan** [comment]
Yes! I think this would be great to add in, both in terms of providing insight for our friends in Wales and as future prep for the 2021 census.

**Comment by Robinlovelace** [comment]
Great, could be a new vignetted. Input very welcome @natesheehan, thanks for the comment!

**Comment by natesheehan** [comment]
Welcome! Yes, I can write a vignette based on the example above ~ this week?

**Comment by Robinlovelace** [comment]
That would be amazing!

**Comment by cristitosa** [comment]
Has there been any documented case studies for cities outside the UK, and the customization of the PCT tool?
Thank you.

**Comment by cristitosa** [comment]
Hi @Robinlovelace thank you for your reply. Good to know! At the moment I am not in Romania, but surely it is needed there as well. Currently a postdoc in Stavanger, Norway, and a PhD student of ours wanted to explore the PCT.
