### ISSUE TITLE
Excessive size of docs folder prevents release on CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/pct#97]
Just got this message from CRAN when trying to release the package:

> Size of tarball: 6231041 bytes

> Not more than 5 MB for a CRAN package, please.

After looking into it, I think it is the 'km cycled' vignette that is the culprit. Looking at it, I guess all the interactive maps here that are to blame: https://itsleeds.github.io/pct/articles/km-cycled.html#comparing-regions

Suggested quickfix: don't switch on `tmap_mode("view")`. We could link to an interactive version, e.g. hosted on rpubs and mention view mode. One other issue is with the calculation of km - will open a separate issue on that. You up for having a go at this @natesheehan? Should be a quick fix. P.s. happy :hatching_chick: time !

**Comment by natesheehan** [comment]
Good find Robin, and happy 🐑  from here in Cornwall (lots of lambs being born this weekend). 

I'll get on pushing the suggested quick fix now  👍

**Comment by natesheehan** [comment]
@Robinlovelace  PR = https://github.com/ITSLeeds/pct/pull/99

**Comment by Robinlovelace** [comment]
Seems have solved it, just resubmitted and seems to be down to 3 MB now:

```
Submitting file: /tmp/Rtmp4fqNGQ/pct_0.8.0.tar.gz
File size: 3.5 Mb
Ready to submit pct (0.8.0) to CRAN?
1: Not yet
2: Definitely
3: I forget

Selection: 2
Uploading package & comments
Confirming submission
Package submission successful.
Check your email for confirmation link.
✔ Setting active project to '/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/atfutures/itsleeds/pct'
Don't forget to tag this release once accepted by CRAN
✔ Setting active project to '<no active project>'
```
